# Generated by Django 5.2.4 on 2026-09-13 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('pacientes', '0007_caso_para_pacientes_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data prevista pela regra')),
                ('inicio', models.DateTimeField(verbose_name='Início')),
                ('duracao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(240)], verbose_name='Duração (minutos)')),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('FALTA', 'Falta'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10, verbose_name='Situação')),
                ('contabilizada', models.BooleanField(default=False, help_text='Só tem efeito depois do registro. Proposto pelo perfil: realizada entra; falta entra se você cobra falta (ADR-023). Ajustável em cada consulta.', verbose_name='Entra na cobrança')),
                ('remarcada', models.BooleanField(default=False, help_text='Uma mudança futura na regra não sobrescreve esta consulta (ADR-022).', verbose_name='Remarcada à mão')),
                ('registrada_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Registrada em')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.caso')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
                ('recorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='agenda.recorrencia')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['psicologo', 'inicio'], name='consulta_dono_inicio')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('recorrencia__isnull', False)), fields=('recorrencia', 'data_prevista'), name='uma_consulta_por_ocorrencia'), models.CheckConstraint(condition=models.Q(models.Q(('data_prevista__isnull', True), ('recorrencia__isnull', True)), models.Q(('data_prevista__isnull', False), ('recorrencia__isnull', False)), _connector='OR'), name='ocorrencia_tem_regra_e_data')],
            },
        ),
    ]
