# Generated by Django 5.2.4 on 2026-09-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_rls'),
        ('pacientes', '0007_caso_para_pacientes_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desfecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta'), ('DESISTENCIA', 'Desistência'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('INTERRUPCAO', 'Interrupção pelo psicólogo')], max_length=15, verbose_name='Desfecho')),
                ('iniciativa', models.CharField(choices=[('PACIENTE', 'Do paciente'), ('PSICOLOGO', 'Do psicólogo')], max_length=10, verbose_name='Iniciativa')),
                ('data', models.DateField(verbose_name='Data')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('retomado_em', models.DateField(blank=True, null=True, verbose_name='Retomado em')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desfechos', to='pacientes.caso')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Desfecho',
                'verbose_name_plural': 'Desfechos',
                'ordering': ['-data', '-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('retomado_em__isnull', True)), fields=('caso',), name='um_desfecho_em_aberto_por_caso'), models.CheckConstraint(condition=models.Q(('retomado_em__isnull', True), ('retomado_em__gte', models.F('data')), _connector='OR'), name='retomada_nao_antes_do_desfecho')],
            },
        ),
    ]
