# Generated by Django 5.2.4 on 2026-09-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_situacoes_da_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='remarcada_para',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Remarcada para'),
        ),
    ]
