# Generated by Django 5.2.4 on 2026-09-17 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_remarcada_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vazio: vale o valor combinado com o paciente.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor desta sessão'),
        ),
    ]
