# Generated by Django 5.2.4 on 2026-09-13 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_papel_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('acao', models.CharField(choices=[('VER', 'Visualizou'), ('CRIAR', 'Criou'), ('ALTERAR', 'Alterou'), ('EXCLUIR', 'Excluiu'), ('EXPORTAR', 'Exportou')], max_length=8, verbose_name='Ação')),
                ('alvo', models.CharField(max_length=60, verbose_name='Tipo do registro')),
                ('alvo_id', models.BigIntegerField(verbose_name='Número do registro')),
                ('titular', models.CharField(max_length=60, verbose_name='Tipo do titular')),
                ('titular_id', models.BigIntegerField(verbose_name='Número do titular')),
                ('campos', models.JSONField(blank=True, default=list, verbose_name='Campos alterados')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['psicologo', 'titular', 'titular_id'], name='auditoria_por_titular')],
            },
        ),
    ]
