# Generated by Django 5.2.4 on 2026-09-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0010_modalidade_do_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Conteúdo')),
                ('emitido_em', models.DateTimeField(blank=True, null=True, verbose_name='Emitido em')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Documento psicológico',
                'verbose_name_plural': 'Documentos psicológicos',
                'ordering': ['-atualizado_em'],
                'indexes': [models.Index(fields=['psicologo', 'modelo'], name='documento_dono_modelo')],
            },
        ),
    ]
