# Generated by Django 5.2.4 on 2026-10-01 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_rls_e_documento_emitido_imutavel'),
        ('pacientes', '0013_endereco_fora_do_brasil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato terapêutico'), ('AUTORIZACAO', 'Autorização ou consentimento'), ('AVALIACAO', 'Anexo de avaliação psicológica'), ('ENCAMINHAMENTO', 'Encaminhamento ou relatório de outro profissional'), ('OUTRO', 'Outro')], default='CONTRATO', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(help_text='Como você reconhece este arquivo na lista.', max_length=160, verbose_name='Título')),
                ('nome_do_arquivo', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('tipo_mime', models.CharField(max_length=80, verbose_name='Formato')),
                ('tamanho', models.PositiveIntegerField(verbose_name='Tamanho em bytes')),
                ('restrito', models.BooleanField(default=False, help_text='Marque para anexo de avaliação e material que não compõe o que o paciente pode solicitar.', verbose_name='Somente eu vejo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Arquivo guardado',
                'verbose_name_plural': 'Arquivos guardados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoDeArquivo',
            fields=[
                ('arquivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='conteudo', serialize=False, to='documentos.arquivoguardado')),
                ('bytes_do_arquivo', models.BinaryField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Conteúdo de arquivo',
                'verbose_name_plural': 'Conteúdos de arquivo',
            },
        ),
        migrations.AddIndex(
            model_name='arquivoguardado',
            index=models.Index(fields=['psicologo', 'paciente'], name='arquivo_dono_paciente'),
        ),
    ]
