# Generated by Django 5.2.4 on 2026-09-13 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0007_caso_para_pacientes_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('frequencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal')], max_length=10, verbose_name='Frequência')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('hora', models.TimeField(verbose_name='Horário')),
                ('duracao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(240)], verbose_name='Duração (minutos)')),
                ('inicio', models.DateField(help_text='Na quinzenal, a primeira sessão a partir desta data define quais semanas são as de atendimento.', verbose_name='Vale a partir de')),
                ('fim', models.DateField(blank=True, help_text='Nenhuma sessão é prevista nesta data nem depois. Vazio enquanto a regra valer.', null=True, verbose_name='Encerrada em')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to='pacientes.caso')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Recorrência',
                'verbose_name_plural': 'Recorrências',
                'ordering': ['-inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='recorrencia_fim_nao_antes_do_inicio')],
            },
        ),
    ]
