# Generated by Django 5.2.4 on 2026-09-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('inicio', models.TimeField(verbose_name='Das')),
                ('fim', models.TimeField(verbose_name='Até')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Horário disponível',
                'verbose_name_plural': 'Horários disponíveis',
                'ordering': ['dia_semana', 'inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='horario_fim_depois_do_inicio')],
            },
        ),
    ]
