# Generated by Django 5.2.4 on 2026-10-02 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_primeira_sessao_fora_do_dia_fixo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(help_text='Como aparece na agenda. Por exemplo: Supervisão do Arthur, Atendimento ONG, Reunião de equipe.', max_length=120, verbose_name='O que é')),
                ('frequencia', models.CharField(choices=[('UNICO', 'Uma vez só'), ('SEMANAL', 'Toda semana'), ('QUINZENAL', 'A cada duas semanas')], default='SEMANAL', max_length=10, verbose_name='Com que frequência')),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da semana')),
                ('hora', models.TimeField(verbose_name='Horário')),
                ('duracao', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(480)], verbose_name='Duração (minutos)')),
                ('inicio', models.DateField(help_text='No compromisso de uma vez só, é o dia dele.', verbose_name='A partir de')),
                ('fim', models.DateField(blank=True, help_text='Nada é previsto nesta data nem depois. Vazio enquanto o compromisso valer.', null=True, verbose_name='Até')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['dia_semana', 'hora', 'titulo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='compromisso_fim_nao_antes_do_inicio'), models.CheckConstraint(condition=models.Q(models.Q(('dia_semana__isnull', True), ('frequencia', 'UNICO')), models.Q(models.Q(('frequencia', 'UNICO'), _negated=True), ('dia_semana__isnull', False)), _connector='OR'), name='compromisso_dia_semana_combina_com_a_frequencia')],
            },
        ),
    ]
