# Generated by Django 5.2.4 on 2026-09-13 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_cadastro_ampliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^(\\d{8})?$', 'CEP tem 8 números, sem traço.')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^(\\d{11})?$', 'CPF tem 11 números, sem pontos ou traços.')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{10,11})?$', 'Telefone com DDD: 10 ou 11 números, sem espaços ou traços.')], verbose_name='Telefone'),
        ),
    ]
