# Generated by Django 5.2.4 on 2026-09-13 17:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_validacao_de_formato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(blank=True, help_text='Ex.: "Maria e João — casal". Vazio no atendimento individual.', max_length=120, verbose_name='Descrição')),
                ('pagador_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do pagador')),
                ('pagador_cpf', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^(\\d{11})?$', 'CPF tem 11 números, sem pontos ou traços.')], verbose_name='CPF do pagador')),
                ('pagador_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_que_paga', to='pacientes.paciente', verbose_name='Pagador (participante)')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='pacientes.caso')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='pacientes',
            field=models.ManyToManyField(related_name='casos', through='pacientes.Participacao', to='pacientes.paciente', verbose_name='Pacientes'),
        ),
        migrations.CreateModel(
            name='ResponsavelLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('parentesco', models.CharField(blank=True, help_text='Ex.: mãe, avô, tutora.', max_length=60, verbose_name='Parentesco')),
                ('cpf', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^(\\d{11})?$', 'CPF tem 11 números, sem pontos ou traços.')], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{10,11})?$', 'Telefone com DDD: 10 ou 11 números, sem espaços ou traços.')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('guarda', models.CharField(choices=[('COMPARTILHADA', 'Compartilhada'), ('UNILATERAL', 'Unilateral'), ('NAO_INFORMADA', 'Não informada')], default='NAO_INFORMADA', max_length=15, verbose_name='Guarda')),
                ('detem_guarda', models.BooleanField(default=True, help_text='Em guarda unilateral, só quem a detém autoriza o atendimento (ADR-014).', verbose_name='Detém a guarda')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Responsável legal',
                'verbose_name_plural': 'Responsáveis legais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CondicaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('modalidade', models.CharField(choices=[('POR_SESSAO', 'Por sessão'), ('MENSAL', 'Mensalidade')], default='POR_SESSAO', max_length=12, verbose_name='Forma de cobrança')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor')),
                ('vencimento', models.CharField(blank=True, choices=[('INICIO', 'Início do mês'), ('FIM', 'Fim do mês')], help_text='Só para mensalidade.', max_length=6, verbose_name='Vencimento')),
                ('vigente_desde', models.DateField(verbose_name='Vale a partir de')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='pacientes.caso')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Condição de cobrança',
                'verbose_name_plural': 'Condições de cobrança',
                'ordering': ['-vigente_desde'],
                'constraints': [models.UniqueConstraint(fields=('caso', 'vigente_desde'), name='uma_condicao_por_data')],
            },
        ),
        migrations.AddConstraint(
            model_name='participacao',
            constraint=models.UniqueConstraint(fields=('caso', 'paciente'), name='paciente_uma_vez_por_caso'),
        ),
    ]
