# Generated by Django 5.2.4 on 2026-09-18 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_modalidade_do_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='documento_estrangeiro',
            field=models.CharField(blank=True, help_text='Passaporte ou RNM, para quem não tem CPF.', max_length=40, verbose_name='Documento (estrangeiro)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('UNIAO_ESTAVEL', 'União estável'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)')], max_length=15, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, max_length=60, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_social',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome social'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=60, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(blank=True, max_length=120, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='raca_cor',
            field=models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena'), ('NAO_INFORMA', 'Prefiro não informar')], max_length=12, verbose_name='Raça/cor'),
        ),
        migrations.CreateModel(
            name='ContatoDeEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('parentesco', models.CharField(blank=True, help_text='Ex.: mãe, irmão, amiga.', max_length=60, verbose_name='Parentesco')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{10,11})?$', 'Telefone com DDD: 10 ou 11 números, sem espaços ou traços.')], verbose_name='Telefone')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_de_emergencia', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Contato de emergência',
                'verbose_name_plural': 'Contatos de emergência',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ConviteDeCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash do token')),
                ('rotulo', models.CharField(blank=True, help_text='Só para você reconhecer o link na lista. O paciente não vê.', max_length=120, verbose_name='Para quem é')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('respostas', models.JSONField(blank=True, default=dict, verbose_name='Respostas')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='Cadastrado em')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_de_cadastro', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Convite de cadastro',
                'verbose_name_plural': 'Convites de cadastro',
                'ordering': ['-criado_em'],
            },
        ),
    ]
