# Generated by Django 5.2.4 on 2026-09-18 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_rls_convite_e_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_exterior',
            field=models.CharField(blank=True, help_text='Só para endereço fora do Brasil.', max_length=60, verbose_name='Estado ou província'),
        ),
        migrations.AlterField(
            model_name='contatodeemergencia',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{6,15})?$', 'Telefone: de 6 a 15 números, com o código do país.')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=12, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='responsavellegal',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{6,15})?$', 'Telefone: de 6 a 15 números, com o código do país.')], verbose_name='Telefone'),
        ),
    ]
