# Generated by Django 5.2.4 on 2026-09-10 01:37

import contas.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Informe apenas números, sem pontos ou traços.')], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Informe apenas números, sem pontos ou traços.')], verbose_name='Telefone')),
                ('crp_regiao', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d+$', 'Informe apenas números, sem pontos ou traços.')], verbose_name='Região do CRP')),
                ('crp_numero', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Informe apenas números, sem pontos ou traços.')], verbose_name='Número do CRP')),
                ('situacao_registro', models.CharField(choices=[('NAO_VERIFICADO', 'Não verificado'), ('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado'), ('TRANSFERIDO', 'Transferido')], default='NAO_VERIFICADO', max_length=20, verbose_name='Situação do registro')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('regime', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], default='PF', max_length=2, verbose_name='Regime')),
                ('cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d+$', 'Informe apenas números, sem pontos ou traços.')], verbose_name='CNPJ')),
                ('crp_empresa', models.CharField(blank=True, max_length=20, verbose_name='CRP da empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
                'constraints': [models.UniqueConstraint(fields=('crp_regiao', 'crp_numero'), name='crp_unico')],
            },
            managers=[
                ('objects', contas.models.PsicologoManager()),
            ],
        ),
    ]
