# Generated by Django 5.2.4 on 2026-09-13 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^(\\d{14})?$', 'CNPJ tem 14 números, sem pontos, barra ou traço.')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF tem 11 números, sem pontos ou traços.')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='crp_regiao',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'A região do CRP tem 2 números, como 04.')], verbose_name='Região do CRP'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone com DDD: 10 ou 11 números, sem espaços ou traços.')], verbose_name='Telefone'),
        ),
    ]
