# Generated by Django 5.2.4 on 2026-09-13 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_validacao_de_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='cobra_falta',
            field=models.BooleanField(default=True, help_text='Se marcado, a falta entra na cobrança por padrão. Ajustável caso a caso (ADR-023).', verbose_name='Cobro falta'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='duracao_sessao',
            field=models.PositiveSmallIntegerField(default=50, help_text='A convenção é 50. Ajustável por paciente: infantil costuma ser mais curta, casal mais longa.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(240)], verbose_name='Duração da sessão (minutos)'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='vencimento_mensalidade',
            field=models.CharField(choices=[('INICIO', 'Início do mês'), ('FIM', 'Fim do mês')], default='INICIO', help_text='Proposto a cada paciente que pagar por mês.', max_length=6, verbose_name='Vencimento da mensalidade'),
        ),
    ]
