# Generated by Django 5.2.4 on 2026-09-17 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_tipo_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='cep',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^(\\d{8})?$', 'CEP tem 8 números, sem traço.')], verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='nome_clinica',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da clínica ou consultório'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razão social'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='telefone_clinica',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{10,11})?$', 'Telefone com DDD: 10 ou 11 números, sem espaços ou traços.')], verbose_name='Telefone da clínica'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'),
        ),
    ]
