# Generated by Django 5.2.4 on 2026-09-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_dados_da_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='abordagem',
            field=models.CharField(blank=True, choices=[('PSICANALISE', 'Psicanálise'), ('TCC', 'Terapia cognitivo-comportamental'), ('ANALITICA', 'Psicologia analítica (junguiana)'), ('GESTALT', 'Gestalt-terapia'), ('HUMANISTA', 'Abordagem centrada na pessoa / humanista'), ('FENOMENOLOGICA', 'Fenomenológico-existencial'), ('COMPORTAMENTAL', 'Análise do comportamento'), ('SISTEMICA', 'Sistêmica / familiar'), ('PSICODRAMA', 'Psicodrama'), ('OUTRA', 'Outra')], max_length=20, verbose_name='Abordagem'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='abordagem_outra',
            field=models.CharField(blank=True, max_length=120, verbose_name='Qual abordagem'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='atende_online',
            field=models.BooleanField(default=False, verbose_name='Atende online'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='atende_presencial',
            field=models.BooleanField(default=True, verbose_name='Atende presencialmente'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='quiz_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cadastro concluído em'),
        ),
    ]
