# Generated by Django 5.2.4 on 2026-09-27 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_cadastro_curto_e_abordagens_escritas'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='usa_despesas',
            field=models.BooleanField(default=True, verbose_name='Controlar despesas'),
        ),
        migrations.CreateModel(
            name='MudancaDeRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('regime_anterior', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], max_length=2, verbose_name='Regime anterior')),
                ('regime_novo', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], max_length=2, verbose_name='Regime novo')),
                ('vigente_desde', models.DateField(verbose_name='Vale a partir de')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Mudança de regime',
                'verbose_name_plural': 'Mudanças de regime',
                'ordering': ['-vigente_desde'],
            },
        ),
    ]
