# Generated by Django 5.2.4 on 2026-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_abordagens_de_lista_fechada'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='usa_ia_no_prontuario',
            field=models.BooleanField(default=False, verbose_name='Escrita assistida no registro de sessão'),
        ),
    ]
