# Generated by Django 5.2.4 on 2026-09-20 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estado', models.CharField(choices=[('TESTE', 'Teste grátis'), ('ATIVA', 'Ativa')], max_length=20, verbose_name='Estado')),
                ('teste_termina_em', models.DateTimeField(blank=True, null=True, verbose_name='Teste termina em')),
                ('ativa_desde', models.DateTimeField(blank=True, null=True, verbose_name='Ativa desde')),
                ('meio', models.CharField(blank=True, choices=[('CARTAO', 'Cartão de crédito'), ('PIX_AUTOMATICO', 'PIX Automático')], max_length=20, verbose_name='Meio de pagamento')),
                ('id_no_gateway', models.CharField(blank=True, max_length=64, verbose_name='Identificador no gateway')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'constraints': [models.UniqueConstraint(fields=('psicologo',), name='uma_assinatura_por_psicologo')],
            },
        ),
    ]
