# Generated by Django 5.2.4 on 2026-09-15 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0005_consulta_cadastrada'),
        ('pacientes', '0009_tipo_vencimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='atendimentos.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
        migrations.CreateModel(
            name='VersaoProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Versão')),
                ('texto', models.TextField(verbose_name='Registro da sessão')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo da correção')),
                ('confirmada_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada em')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='prontuarios.prontuario')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Versão de prontuário',
                'verbose_name_plural': 'Versões de prontuário',
                'ordering': ['numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='prontuario',
            constraint=models.UniqueConstraint(fields=('consulta', 'paciente'), name='um_prontuario_por_participante_por_sessao'),
        ),
        migrations.AddConstraint(
            model_name='versaoprontuario',
            constraint=models.UniqueConstraint(fields=('prontuario', 'numero'), name='numero_de_versao_unico'),
        ),
        migrations.AddConstraint(
            model_name='versaoprontuario',
            constraint=models.UniqueConstraint(condition=models.Q(('confirmada_em__isnull', True)), fields=('prontuario',), name='um_rascunho_por_prontuario'),
        ),
    ]
