# Generated by Django 5.2.4 on 2026-09-18 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_modalidade_do_paciente'),
        ('prontuarios', '0002_rls_e_versao_imutavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDoProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('demanda', models.TextField(blank=True, verbose_name='Avaliação da demanda e objetivos do trabalho')),
                ('encerramento', models.TextField(blank=True, verbose_name='Encaminhamento ou encerramento')),
                ('registrada_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrada em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_do_prontuario', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Ficha do prontuário',
                'verbose_name_plural': 'Fichas do prontuário',
                'ordering': ['-registrada_em', '-pk'],
            },
        ),
    ]
