# Generated by Django 5.2.4 on 2026-09-18 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_endereco_fora_do_brasil'),
        ('prontuarios', '0004_rls_e_ficha_imutavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('queixa_principal', models.TextField(blank=True, verbose_name='Queixa principal')),
                ('historia_da_queixa', models.TextField(blank=True, verbose_name='História da queixa')),
                ('tratamentos_anteriores', models.TextField(blank=True, verbose_name='Tratamentos anteriores')),
                ('saude_geral', models.TextField(blank=True, verbose_name='Saúde geral')),
                ('sono_alimentacao_substancias', models.TextField(blank=True, verbose_name='Sono, alimentação e uso de substâncias')),
                ('historia_familiar', models.TextField(blank=True, verbose_name='História familiar')),
                ('desenvolvimento', models.TextField(blank=True, verbose_name='Desenvolvimento e infância')),
                ('escolaridade_e_trabalho', models.TextField(blank=True, verbose_name='Escolaridade e trabalho')),
                ('relacionamentos', models.TextField(blank=True, verbose_name='Relacionamentos e rede de apoio')),
                ('rotina_e_lazer', models.TextField(blank=True, verbose_name='Rotina e lazer')),
                ('expectativas', models.TextField(blank=True, verbose_name='Expectativas com a terapia')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do psicólogo')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anamnese', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
    ]
