# Generated by Django 5.2.4 on 2026-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0008_rls_anamnese_por_blocos'),
    ]

    operations = [
        migrations.AddField(
            model_name='versaoprontuario',
            name='origem',
            field=models.CharField(choices=[('MAO', 'Escrito à mão'), ('IA', 'Rascunho gerado com apoio de IA')], default='MAO', max_length=3, verbose_name='Origem do texto'),
        ),
    ]
