# Generated by Django 5.2.4 on 2026-09-15 21:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0005_consulta_cadastrada'),
        ('pacientes', '0009_tipo_vencimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mes_referencia', models.DateField(blank=True, help_text='Primeiro dia do mês da mensalidade.', null=True, verbose_name='Mês de referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Pago em')),
                ('forma', models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência')], max_length=13, verbose_name='Forma de pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pacientes.caso')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='atendimentos.consulta', verbose_name='Sessão')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data', '-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('consulta__isnull', True), ('mes_referencia__isnull', False)), models.Q(('consulta__isnull', False), ('mes_referencia__isnull', True)), _connector='OR'), name='pagamento_de_um_mes_ou_de_uma_sessao')],
            },
        ),
    ]
