# Generated by Django 5.2.4 on 2026-09-18 19:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=120, verbose_name='Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('mensal', models.BooleanField(default=False, verbose_name='Repete todo mês')),
                ('fim', models.DateField(blank=True, help_text='Só para despesa mensal que acabou: o último mês em que ela aparece.', null=True, verbose_name='Último mês')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['vencimento', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='BaixaDeDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mes', models.DateField(help_text='Primeiro dia do mês da ocorrência.', verbose_name='Mês')),
                ('pago_em', models.DateField(verbose_name='Pago em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor pago')),
                ('psicologo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.despesa')),
            ],
            options={
                'verbose_name': 'Baixa de despesa',
                'verbose_name_plural': 'Baixas de despesa',
                'constraints': [models.UniqueConstraint(fields=('despesa', 'mes'), name='uma_baixa_por_despesa_por_mes')],
            },
        ),
    ]
