# Generated by Django 5.2.4 on 2026-09-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_rls_despesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('ALUGUEL', 'Aluguel do consultório'), ('CONDOMINIO_IPTU', 'Condomínio e IPTU do consultório'), ('CONTAS_DO_CONSULTORIO', 'Água, luz e gás do consultório'), ('INTERNET_TELEFONE', 'Internet e telefone'), ('LIMPEZA_MANUTENCAO', 'Limpeza e manutenção do consultório'), ('BENFEITORIA_ALUGADO', 'Benfeitoria em imóvel alugado'), ('CASA_PROPORCIONAL', 'Parte da casa usada para atender'), ('MATERIAL', 'Material de trabalho e de escritório'), ('SISTEMAS', 'Sistemas e ferramentas de trabalho'), ('PESSOAL', 'Salário e encargos de funcionário'), ('SERVICOS_DE_TERCEIROS', 'Serviços contratados para a atividade'), ('DIVULGACAO', 'Divulgação profissional'), ('FORMACAO', 'Congresso, curso e publicação da área'), ('SUPERVISAO', 'Supervisão clínica'), ('CRP', 'Anuidade do CRP'), ('TRANSPORTE', 'Transporte e veículo'), ('EQUIPAMENTO', 'Compra de equipamento e móveis'), ('IMOVEL_PROPRIO', 'Reforma de imóvel próprio'), ('PESSOAL_DO_PSICOLOGO', 'Despesa pessoal'), ('OUTRA', 'Outra despesa')], default='OUTRA', max_length=30, verbose_name='Categoria'),
        ),
    ]
